// Dummy data + shared constants for the tickets dashboard.
// Replace with real API data once the backend endpoint is wired up.

export const STATUS = {
  RTT: 'RTT',                 // Assigned to agent, not yet started
  IN_PROGRESS: 'IN_PROGRESS',
  ON_HOLD: 'ON_HOLD',
  READY_TO_QC: 'READY_TO_QC',
  IN_QC: 'IN_QC',
  REJECTED: 'REJECTED',        // Sent back by QC to the original agent
  TRAFFICKED: 'TRAFFICKED',    // Fully approved and live
};

// Display metadata per status — drives both the status pill and, where
// relevant, which dropdown options are offered.
export const STATUS_META = {
  [STATUS.RTT]: { text: 'RTT', className: 'status-rtt' },
  [STATUS.IN_PROGRESS]: { text: 'In Progress', className: 'status-in-progress' },
  [STATUS.ON_HOLD]: { text: 'On Hold', className: 'status-on-hold' },
  [STATUS.READY_TO_QC]: { text: 'Ready to QC', className: 'status-ready-qc' },
  [STATUS.IN_QC]: { text: 'In QC', className: 'status-in-qc' },
  [STATUS.REJECTED]: { text: 'Rejected', className: 'status-rejected' },
  [STATUS.TRAFFICKED]: { text: 'Trafficked', className: 'status-trafficked' },
};

// Operator roster used both for the editable Operator picker (RTT tab)
// and the Reassign flow on Rejected tickets.
export const OPERATORS = [
  'Priya Nair',
  'Arjun Mehta',
  'Sara Thomas',
  'Devika Rao',
];

const baseFields = {
  marketingCampaign: 'Netflix Music',
  adTech: 'Non-Debut',
  taskType: 'Social Post',
  page: 'Netflix Music',
  platform: 'Instagram',
  region: 'US',
  highVisibilityTitles: 'Yes',
  launchingPrioritization: 'Yes',
};

export const initialMockTickets = [
  {
    id: 'TCK-1042',
    subject: 'Netflix Music — Non-Debut campaign assets',
    assignee: 'Priya Nair',
    operator: 'Priya Nair',
    status: STATUS.RTT,
    ...baseFields,
    taskReceivedTime: '2026-07-15 08:30 AM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-014',
    adName: 'Ad-Music-014-A',
    flightStart: '2026-07-16 09:00 AM',
    flightEnd: '2026-07-30 11:59 PM',
    taskAssignedTime: '2026-07-15 08:45 AM',
    publishDate: '2026-07-16 (PST)',
    socialiteNotes: 'Assets ready in Socialite library.',
    traffickerComments: '',
    qcThread: '—',
    qcer: '',
    qcStatus: '',
    qcComment: '',
    updatedAt: '2026-07-15 08:45 AM',
  },
  {
    id: 'TCK-1043',
    subject: 'Calendar invite — Debut launch recheck',
    assignee: 'Arjun Mehta',
    operator: 'Arjun Mehta',
    status: STATUS.RTT,
    ...baseFields,
    adTech: 'Debut',
    taskReceivedTime: '2026-07-15 08:50 AM',
    campaignName: 'Debut Q3 Push',
    adSetName: 'AdSet-Debut-002',
    adName: 'Ad-Debut-002-B',
    flightStart: '2026-07-17 10:00 AM',
    flightEnd: '2026-08-01 11:59 PM',
    taskAssignedTime: '2026-07-15 09:00 AM',
    publishDate: '2026-07-17 (PST)',
    socialiteNotes: 'Awaiting final creative sign-off.',
    traffickerComments: '',
    qcThread: '—',
    qcer: '',
    qcStatus: '',
    qcComment: '',
    updatedAt: '2026-07-15 09:00 AM',
  },
  {
    id: 'TCK-1044',
    subject: 'Netflix Music — Non-Debut thumbnail set',
    assignee: 'Sara Thomas',
    operator: 'Sara Thomas',
    status: STATUS.IN_PROGRESS,
    ...baseFields,
    taskReceivedTime: '2026-07-15 07:30 AM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-015',
    adName: 'Ad-Music-015-A',
    flightStart: '2026-07-16 09:00 AM',
    flightEnd: '2026-07-30 11:59 PM',
    taskAssignedTime: '2026-07-15 07:45 AM',
    publishDate: '2026-07-16 (PST)',
    socialiteNotes: 'Thumbnails uploaded, cropping in progress.',
    traffickerComments: 'Please confirm aspect ratio before submitting.',
    qcThread: '—',
    qcer: '',
    qcStatus: '',
    qcComment: '',
    updatedAt: '2026-07-15 09:40 AM',
  },
  {
    id: 'TCK-1045',
    subject: 'Regional campaign — copy localization',
    assignee: 'Devika Rao',
    operator: 'Devika Rao',
    status: STATUS.IN_PROGRESS,
    ...baseFields,
    marketingCampaign: 'Regional Push',
    page: 'Netflix LatAm',
    region: 'LATAM',
    taskReceivedTime: '2026-07-15 08:00 AM',
    campaignName: 'LatAm Expansion',
    adSetName: 'AdSet-Regional-007',
    adName: 'Ad-Regional-007-C',
    flightStart: '2026-07-18 09:00 AM',
    flightEnd: '2026-08-02 11:59 PM',
    taskAssignedTime: '2026-07-15 08:15 AM',
    publishDate: '2026-07-18 (PST)',
    socialiteNotes: 'Translated copy pending legal review.',
    traffickerComments: 'Legal flagged one line, revising now.',
    qcThread: '—',
    qcer: '',
    qcStatus: '',
    qcComment: '',
    updatedAt: '2026-07-15 08:55 AM',
  },
  {
    id: 'TCK-1046',
    subject: 'Social post — Regional campaign copy review',
    assignee: 'Sara Thomas',
    operator: 'Sara Thomas',
    status: STATUS.ON_HOLD,
    ...baseFields,
    marketingCampaign: 'Regional Push',
    page: 'Netflix LatAm',
    region: 'LATAM',
    taskReceivedTime: '2026-07-15 07:10 AM',
    campaignName: 'LatAm Expansion',
    adSetName: 'AdSet-Regional-006',
    adName: 'Ad-Regional-006-A',
    flightStart: '2026-07-17 09:00 AM',
    flightEnd: '2026-08-01 11:59 PM',
    taskAssignedTime: '2026-07-15 07:20 AM',
    publishDate: '2026-07-17 (PST)',
    socialiteNotes: 'Waiting on trafficker for clarification.',
    traffickerComments: 'Checking with brand team on approved wording.',
    qcThread: '—',
    qcer: '',
    qcStatus: '',
    qcComment: '',
    updatedAt: '2026-07-15 08:55 AM',
  },
  {
    id: 'TCK-1047',
    subject: 'Netflix Music — Non-Debut carousel ad',
    assignee: 'Priya Nair',
    operator: 'Priya Nair',
    status: STATUS.READY_TO_QC,
    ...baseFields,
    taskReceivedTime: '2026-07-15 06:45 AM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-013',
    adName: 'Ad-Music-013-D',
    flightStart: '2026-07-16 09:00 AM',
    flightEnd: '2026-07-30 11:59 PM',
    taskAssignedTime: '2026-07-15 07:00 AM',
    publishDate: '2026-07-16 (PST)',
    socialiteNotes: 'All assets finalized and submitted.',
    traffickerComments: 'Looks good from my side.',
    qcThread: 'Thread #4821',
    qcer: '',
    qcStatus: 'Pending review',
    qcComment: '',
    updatedAt: '2026-07-15 10:03 AM',
  },
  {
    id: 'TCK-1048',
    subject: 'Netflix Music — Non-Debut story ad set',
    assignee: 'Devika Rao',
    operator: 'Devika Rao',
    status: STATUS.IN_QC,
    ...baseFields,
    taskReceivedTime: '2026-07-14 06:30 PM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-011',
    adName: 'Ad-Music-011-A',
    flightStart: '2026-07-16 09:00 AM',
    flightEnd: '2026-07-30 11:59 PM',
    taskAssignedTime: '2026-07-14 06:45 PM',
    publishDate: '2026-07-16 (PST)',
    socialiteNotes: 'Submitted for QC last night.',
    traffickerComments: 'No issues flagged pre-QC.',
    qcThread: 'Thread #4802',
    qcer: 'Meera Iyer',
    qcStatus: 'In review',
    qcComment: '',
    updatedAt: '2026-07-15 09:10 AM',
  },
  {
    id: 'TCK-1049',
    subject: 'Trailer copy — QA flagged mismatch',
    assignee: 'Priya Nair',
    operator: 'Priya Nair',
    status: STATUS.REJECTED,
    ...baseFields,
    taskReceivedTime: '2026-07-14 03:00 PM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-009',
    adName: 'Ad-Music-009-B',
    flightStart: '2026-07-16 09:00 AM',
    flightEnd: '2026-07-30 11:59 PM',
    taskAssignedTime: '2026-07-14 03:15 PM',
    publishDate: '2026-07-16 (PST)',
    socialiteNotes: 'Resubmission required per QC note.',
    traffickerComments: 'Please align title casing with brand guide.',
    qcThread: 'Thread #4790',
    qcer: 'Meera Iyer',
    qcStatus: 'Rejected',
    qcComment: 'Title casing does not match brand guide.',
    updatedAt: '2026-07-15 10:20 AM',
  },
  {
    id: 'TCK-1050',
    subject: 'Netflix Music — Non-Debut launch post',
    assignee: 'Arjun Mehta',
    operator: 'Arjun Mehta',
    status: STATUS.TRAFFICKED,
    ...baseFields,
    taskReceivedTime: '2026-07-13 09:00 AM',
    campaignName: 'Summer Drop 2026',
    adSetName: 'AdSet-Music-005',
    adName: 'Ad-Music-005-A',
    flightStart: '2026-07-14 09:00 AM',
    flightEnd: '2026-07-28 11:59 PM',
    taskAssignedTime: '2026-07-13 09:15 AM',
    publishDate: '2026-07-14 (PST)',
    socialiteNotes: 'Live and performing as expected.',
    traffickerComments: 'Confirmed live in Ads Manager.',
    qcThread: 'Thread #4750',
    qcer: 'Meera Iyer',
    qcStatus: 'Approved',
    qcComment: '',
    updatedAt: '2026-07-14 10:00 AM',
  },
  {
    id: 'TCK-1051',
    subject: 'Regional campaign — banner copy mismatch',
    assignee: 'Devika Rao',
    operator: 'Devika Rao',
    status: STATUS.REJECTED,
    ...baseFields,
    marketingCampaign: 'Regional Push',
    page: 'Netflix LatAm',
    region: 'LATAM',
    taskReceivedTime: '2026-07-14 11:00 AM',
    campaignName: 'LatAm Expansion',
    adSetName: 'AdSet-Regional-008',
    adName: 'Ad-Regional-008-B',
    flightStart: '2026-07-17 09:00 AM',
    flightEnd: '2026-08-01 11:59 PM',
    taskAssignedTime: '2026-07-14 11:15 AM',
    publishDate: '2026-07-17 (PST)',
    socialiteNotes: 'Resubmission required per QC note.',
    traffickerComments: 'Banner copy does not match approved localization.',
    qcThread: 'Thread #4795',
    qcer: 'Meera Iyer',
    qcStatus: 'Rejected',
    qcComment: 'Localized copy uses outdated tagline — update to Q3 messaging.',
    updatedAt: '2026-07-15 11:05 AM',
  },
];