// src/components/organicSocial/qa/QADashboardConstants.js

export const globalFont = "'Netflix Sans','Helvetica Neue','Segoe UI',Roboto,Arial,sans-serif";

export const DUMMY_QA_TICKETS = [
  {
    id: 'QA-001',
    taskName: 'Netflix Korea Shorts Upload',
    taskType: 'AV Single Post',
    assignedAgent: 'Snehitha',
    qaStatus: 'Pending Review',
    visibility: 'Yes',
    qaComment: '',
    taskReceivedTime: new Date().toISOString(),
    publishDateRaw: new Date(Date.now() + 86400000).toISOString(),
    socialiteLink: 'https://example.com/socialite/1',
  },
  {
    id: 'QA-002',
    taskName: 'Global Debut AV Post',
    taskType: 'AV Global Debut',
    assignedAgent: 'Sarthak',
    qaStatus: 'Approved',
    visibility: 'No',
    qaComment: 'Looks good!',
    taskReceivedTime: new Date(Date.now() - 3600000).toISOString(),
    publishDateRaw: new Date(Date.now() + 172800000).toISOString(),
    socialiteLink: 'https://example.com/socialite/2',
  },
  {
    id: 'QA-003',
    taskName: 'Community Post - France',
    taskType: 'France Community',
    assignedAgent: 'Nishanth',
    qaStatus: 'QA Fail',
    visibility: 'No',
    qaComment: 'Missing thumbnail',
    taskReceivedTime: new Date(Date.now() - 7200000).toISOString(),
    publishDateRaw: new Date(Date.now() + 259200000).toISOString(),
    socialiteLink: '',
  },
  {
    id: 'QA-004',
    taskName: 'Thumbnail Creation - Anime',
    taskType: 'Thumbnail Creation',
    assignedAgent: 'Harsha',
    qaStatus: 'Re-Assigned',
    visibility: 'Yes',
    qaComment: '',
    taskReceivedTime: new Date(Date.now() - 10800000).toISOString(),
    publishDateRaw: new Date(Date.now() + 345600000).toISOString(),
    socialiteLink: 'https://example.com/socialite/4',
  },
  {
    id: 'QA-005',
    taskName: 'Japan Feed - Weekly',
    taskType: 'Japan-Feed',
    assignedAgent: 'Snehitha',
    qaStatus: 'Approved',
    visibility: 'No',
    qaComment: 'All verified',
    taskReceivedTime: new Date(Date.now() - 86400000).toISOString(),
    publishDateRaw: new Date(Date.now() - 3600000).toISOString(),
    socialiteLink: 'https://example.com/socialite/5',
  },
];